language: cpp

services:
  - docker

branches:
  only:
    - master
    - /v\d+\.\d+.*/

env:
  - DOCKER_IMAGE=knapsu/plexmediaplayer-build:latest

before_script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/plex -w /plex --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}

script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - docker exec -t builder ./scripts/build.sh
  - ./scripts/upload.sh --scp

after_script:
  - docker stop builder

cache:
  directories:
  - cache
