language: cpp

services:
  - docker

branches:
  only:
    - master
    - check

env:
  - DOCKER_IMAGE=knapsu/plex-media-player-appimage:xenial

before_script:
  - docker pull ${DOCKER_IMAGE}
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_0a6514d873f3_key -iv $encrypted_0a6514d873f3_iv -in keys/id_rsa.enc -out keys/id_rsa -d
  - chmod go-rwx keys/id_rsa
  - openssl aes-256-cbc -K $encrypted_e3dcbab1132f_key -iv $encrypted_e3dcbab1132f_iv -in keys/pgp-appimage.asc.enc -out keys/pgp-appimage.asc -d

script:
  - env | grep -E "^TRAVIS|^DOCKER|^PLEX" > travis.env
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/plex --workdir /plex --env-file travis.env --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}
  - docker exec -t builder ./scripts/build.sh
  - ./scripts/upload.sh --scp

after_script:
  - docker stop builder

cache:
  directories:
  - cache
