language: cpp

services:
  - docker

branches:
  only:
    - master
    - check

env:
  - DOCKER_IMAGE=knapsu/plexmediaplayer-build:latest

before_script:
  - docker pull ${DOCKER_IMAGE}
  - env | grep -E "^TRAVIS|^DOCKER" > travis.env
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/plex -w /plex --env-file travis.env --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}

script:
  - docker exec -t builder ./scripts/check.sh

after_script:
  - docker stop builder

cache:
  directories:
  - cache
