name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docker/**'
      - '**/*.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: knapsu/plex-media-player-appimage:xenial
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build script
        run: ./scripts/build.sh
